"""add cascade deletes

Revision ID: 093110adc406
Revises: 517ada252b3c
Create Date: 2026-07-27 19:23:57.814406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093110adc406'
down_revision: Union[str, Sequence[str], None] = '517ada252b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunks_section_id_fkey'), 'chunks', type_='foreignkey')
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_contents_document_id_fkey'), 'document_contents', type_='foreignkey')
    op.create_foreign_key(None, 'document_contents', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_course_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('jobs_document_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sections_document_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_document_id_fkey'), 'sections', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_document_id_fkey'), 'jobs', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_course_id_fkey'), 'documents', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'document_contents', type_='foreignkey')
    op.create_foreign_key(op.f('document_contents_document_id_fkey'), 'document_contents', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('chunks_section_id_fkey'), 'chunks', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###
