"""change document_id to scope_id and add scope to artifacts table

Revision ID: 517ada252b3c
Revises: d105869c0489
Create Date: 2026-07-27 16:45:23.313600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517ada252b3c'
down_revision: Union[str, Sequence[str], None] = 'd105869c0489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('scope', sa.String(), nullable=False))
    op.add_column('artifacts', sa.Column('scope_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('artifacts_document_id_fkey'), 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('artifacts_document_id_fkey'), 'artifacts', 'documents', ['document_id'], ['id'])
    op.drop_column('artifacts', 'scope_id')
    op.drop_column('artifacts', 'scope')
    # ### end Alembic commands ###
