"""edit document contents table

Revision ID: 5b00eba4f1f9
Revises: a9a7f8c75e5f
Create Date: 2026-07-21 18:14:56.046852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b00eba4f1f9'
down_revision: Union[str, Sequence[str], None] = 'a9a7f8c75e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_contents', sa.Column('metadata', sa.JSON(), nullable=True))
    op.drop_column('document_contents', 'location')
    op.drop_column('document_contents', 'confidence')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document_contents', sa.Column('confidence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document_contents', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('document_contents', 'metadata')
    # ### end Alembic commands ###
