"""edit chunks table

Revision ID: ecaff85d7604
Revises: f5ca17ebdc02
Create Date: 2026-07-24 13:57:24.420671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecaff85d7604'
down_revision: Union[str, Sequence[str], None] = 'f5ca17ebdc02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('document_id', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    op.alter_column('chunks', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'])
    op.drop_column('chunks', 'created_at')
    op.drop_column('chunks', 'token_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chunks', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.alter_column('chunks', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chunks', 'embedding')
    op.drop_column('chunks', 'document_id')
    # ### end Alembic commands ###
